// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logstream} from '../models';
import {main} from '../models';
import {adb} from '../models';
import {operations} from '../models';
import {scripts} from '../models';
import {frida} from '../models';

export function ClearLogs():Promise<void>;

export function GetLogs():Promise<Array<logstream.Entry>>;

export function GetSystemStatus():Promise<main.SystemStatus>;

export function ImportScriptFile():Promise<main.ImportedScript>;

export function ListApps(arg1:string,arg2:boolean):Promise<Array<adb.AndroidApp>>;

export function ListDevices():Promise<Array<adb.Device>>;

export function ListOperations():Promise<Array<operations.Template>>;

export function ListProcesses(arg1:string):Promise<Array<adb.Process>>;

export function ListScripts():Promise<Array<scripts.Template>>;

export function ListSessions():Promise<Array<frida.SessionInfo>>;

export function RunOperation(arg1:main.RunOperationRequest):Promise<void>;

export function RunScript(arg1:main.RunScriptRequest):Promise<frida.SessionInfo>;

export function StartFridaServer(arg1:main.FridaServerRequest):Promise<void>;

export function StopSession(arg1:string):Promise<void>;
