// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function ImportScriptFile() {
  return window['go']['main']['App']['ImportScriptFile']();
}

export function ListApps(arg1, arg2) {
  return window['go']['main']['App']['ListApps'](arg1, arg2);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListOperations() {
  return window['go']['main']['App']['ListOperations']();
}

export function ListProcesses(arg1) {
  return window['go']['main']['App']['ListProcesses'](arg1);
}

export function ListScripts() {
  return window['go']['main']['App']['ListScripts']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function RunOperation(arg1) {
  return window['go']['main']['App']['RunOperation'](arg1);
}

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function StartFridaServer(arg1) {
  return window['go']['main']['App']['StartFridaServer'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}
